/* Search Action types */
export const REQUEST_DATA = 'REQUEST_DATA';
export const RECEIVE_ARTIST_DATA = 'RECEIVE_ARTIST_DATA';
export const RECEIVE_TRACK_DATA = 'RECEIVE_TRACK_DATA';
export const RECEIVE_ALBUM_DATA = 'RECEIVE_ALBUM_DATA';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';
export const TRACK_SELECTED = 'TRACK_SELECTED';
export const ARTIST_SELECTED = 'ARTIST_SELECTED';
export const ALBUM_SELECTED = 'ALBUM_SELECTED';
/* Player Action types */
export const PLAY_VIDEO = 'PLAY_VIDEO';
export const RECEIVE_VIDEO_DATA = 'RECEIVE_VIDEO_DATA';
export const LAST_FM_API_REQUEST = 'LAST_FM_API_REQUEST';

